<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string></string>
	<key>fileTypes</key>
	<array>
		<string>wast</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\(</string>
	<key>foldingStopMarker</key>
	<string>\)</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>WebAssembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.wasm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.wasm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.wasm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\(;.*;\)</string>
			<key>name</key>
			<string>comment.block.wasm</string>
		</dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])block(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])loop(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])if(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])then(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])else(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])end(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])try(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])catch(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])catch_all(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])unreachable(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])br(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])br_if(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])br_table(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])return(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])call_indirect(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])call(?=[\s=();])</string><key>name</key><string>entity.name.function.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])drop(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])select(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])local\.get(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])local\.set(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])local\.tee(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])global\.get(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])global\.set(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])table\.get(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])table\.set(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])nop(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])memory\.size(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])memory\.grow(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.load8_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.load8_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.load16_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.load16_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.load8_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.load8_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.load16_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.load16_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.load32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.load32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.store8(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.store16(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.store8(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.store16(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.store32(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.load(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.load(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.load(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.load(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.store(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.store(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.store(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.store(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.const(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.const(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.const(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.const(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.eqz(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.eq(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.ne(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.lt_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.lt_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.gt_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.gt_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.le_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.le_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.ge_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.ge_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.eqz(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.eq(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.ne(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.lt_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.lt_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.gt_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.gt_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.le_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.le_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.ge_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.ge_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.eq(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.ne(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.lt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.gt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.le(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.ge(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.eq(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.ne(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.lt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.gt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.le(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.ge(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.clz(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.ctz(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.popcnt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.mul(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.div_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.div_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.rem_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.rem_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.and(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.or(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.xor(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.shl(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.shr_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.shr_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.rotl(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.rotr(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.clz(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.ctz(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.popcnt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.mul(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.div_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.div_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.rem_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.rem_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.and(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.or(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.xor(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.shl(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.shr_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.shr_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.rotl(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.rotr(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.abs(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.neg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.ceil(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.floor(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.trunc(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.nearest(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.sqrt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.mul(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.div(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.min(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.max(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.copysign(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.abs(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.neg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.ceil(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.floor(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.trunc(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.nearest(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.sqrt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.mul(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.div(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.min(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.max(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.copysign(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.wrap_i64(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_f32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_f32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_f64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_f64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.extend_i32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.extend_i32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_f32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_f32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_f64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_f64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.convert_i32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.convert_i32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.convert_i64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.convert_i64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.demote_f64(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.convert_i32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.convert_i32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.convert_i64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.convert_i64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.promote_f32(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.reinterpret_f32(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.reinterpret_f64(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.reinterpret_i32(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.reinterpret_i64(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.extend8_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.extend16_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.extend8_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.extend16_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.extend32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])ref\.null(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])ref\.is_null(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])ref\.func(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.const(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.store(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.splat(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.splat(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.splat(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.splat(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.splat(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.splat(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.extract_lane_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.extract_lane_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.extract_lane_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.extract_lane_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.extract_lane(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.extract_lane(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.extract_lane(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.extract_lane(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.replace_lane(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.replace_lane(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.replace_lane(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.replace_lane(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.replace_lane(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.replace_lane(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.swizzle(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.shuffle(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load8_splat(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load16_splat(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load32_splat(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load64_splat(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.narrow_i16x8_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.narrow_i16x8_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.narrow_i32x4_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.narrow_i32x4_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.extend_low_i8x16_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.extend_high_i8x16_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.extend_low_i8x16_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.extend_high_i8x16_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.extend_low_i16x8_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.extend_high_i16x8_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.extend_low_i16x8_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.extend_high_i16x8_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.mul(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.mul(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.mul(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.neg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.neg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.neg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.neg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.add_sat_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.add_sat_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.add_sat_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.add_sat_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.sub_sat_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.sub_sat_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.sub_sat_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.sub_sat_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.min_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.min_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.min_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.min_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.min_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.min_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.min_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.min_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.max_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.max_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.max_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.max_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.max_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.max_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.max_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.max_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.avgr_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.avgr_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.shl(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.shl(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.shl(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.shl(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.shr_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.shr_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.shr_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.shr_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.shr_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.shr_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.shr_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.shr_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.and(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.or(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.xor(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.not(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.bitselect(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.any_true(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.all_true(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.all_true(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.all_true(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.all_true(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.eq(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.eq(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.eq(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.eq(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.eq(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.ne(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.ne(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.ne(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.ne(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.ne(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.lt_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.lt_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.lt_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.lt_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.lt_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.lt_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.lt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.lt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.le_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.le_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.le_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.le_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.le_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.le_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.le(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.le(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.gt_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.gt_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.gt_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.gt_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.gt_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.gt_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.gt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.gt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.ge_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.ge_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.ge_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.ge_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.ge_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.ge_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.ge(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.ge(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.neg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.neg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.abs(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.abs(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.min(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.min(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.max(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.max(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.div(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.div(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.mul(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.mul(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.sqrt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.sqrt(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.convert_i32_sx4(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.convert_i32_ux4(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.convert_i64_sx2(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.convert_i64_ux2(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.trunc_sat_f32x4_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.trunc_sat_f32x4_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.trunc_sat_f64x2_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.trunc_sat_f64x2_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load8x8_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load8x8_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load16x4_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load16x4_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load32x2_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.load32x2_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v128\.andnot(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v8x16\.load_interleaved_2(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v8x16\.load_interleaved_3(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v8x16\.load_interleaved_4(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v16x8\.load_interleaved_2(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v16x8\.load_interleaved_3(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v16x8\.load_interleaved_4(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v32x4\.load_interleaved_2(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v32x4\.load_interleaved_3(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v32x4\.load_interleaved_4(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v64x2\.load_interleaved_2(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v64x2\.load_interleaved_3(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v64x2\.load_interleaved_4(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v8x16\.store_interleaved_2(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v8x16\.store_interleaved_3(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v8x16\.store_interleaved_4(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v16x8\.store_interleaved_2(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v16x8\.store_interleaved_3(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v16x8\.store_interleaved_4(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v32x4\.store_interleaved_2(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v32x4\.store_interleaved_3(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v32x4\.store_interleaved_4(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v64x2\.store_interleaved_2(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v64x2\.store_interleaved_3(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])v64x2\.store_interleaved_4(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i8x16\.ltz_mask(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i16x8\.ltz_mask(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.ltz_mask(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])atomic\.notify(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.wait(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.wait(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])atomic\.fence(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.load(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.load(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.load8_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.load16_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.load8_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.load16_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.load32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.store(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.store(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.store8(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.store16(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.store8(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.store16(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.store32(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw\.add(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw8\.add_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw16\.add_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw8\.add_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw16\.add_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw32\.add_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw\.sub(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw8\.sub_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw16\.sub_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw8\.sub_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw16\.sub_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw32\.sub_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw\.and(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw\.and(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw8\.and_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw16\.and_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw8\.and_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw16\.and_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw32\.and_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw\.or(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw\.or(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw8\.or_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw16\.or_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw8\.or_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw16\.or_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw32\.or_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw\.xor(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw\.xor(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw8\.xor_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw16\.xor_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw8\.xor_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw16\.xor_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw32\.xor_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw\.xchg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw\.xchg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw8\.xchg_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw16\.xchg_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw8\.xchg_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw16\.xchg_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw32\.xchg_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw\.cmpxchg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw\.cmpxchg(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw8\.cmpxchg_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.atomic\.rmw16\.cmpxchg_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw8\.cmpxchg_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw16\.cmpxchg_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.atomic\.rmw32\.cmpxchg_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])throw(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])rethrow(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_sat_f32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_sat_f32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_sat_f64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_sat_f64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_sat_f32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_sat_f32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_sat_f64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_sat_f64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])memory\.init(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])data\.drop(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])memory\.copy(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])memory\.fill(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])table\.init(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])elem\.drop(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])table\.copy(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>

		<dict><key>match</key><string>(?&lt;=[\s=();])get_local(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])set_local(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])tee_local(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])get_global(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])set_global(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.convert_i32x4_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32x4\.convert_i32x4_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.convert_i64x2_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64x2\.convert_i64x2_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.trunc_sat_f32x4_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32x4\.trunc_sat_f32x4_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.trunc_sat_f64x2_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64x2\.trunc_sat_f64x2_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_f32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_f32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_f64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_f64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.extend_i32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.extend_i32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_f32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_f32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_f64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_f64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.convert_i32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.convert_i32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.convert_i64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f32\.convert_i64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.convert_i32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.convert_i32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.convert_i64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])f64\.convert_i64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_sat_f32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_sat_f32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_sat_f64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i32\.trunc_sat_f64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_sat_f32_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_sat_f32_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_sat_f64_s(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict><key>match</key><string>(?&lt;=[\s=();])i64\.trunc_sat_f64_u(?=[\s=();])</string><key>name</key><string>keyword.operator.wasm</string></dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])(module|binary|quote|memory|table|data|elem|passive|type|import|export|global|exception_type|ref\.host|func|param|result|local|calling_conv)(?=[\s=();])</string>
			<key>name</key>
			<string>entity.name.function.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])(assert_return|assert_return_arithmetic|assert_return_canonical_nan|assert_return_func|assert_trap|assert_throws|assert_invalid|assert_malformed|assert_unlinkable|invoke|get)(?=[\s=();])</string>
			<key>name</key>
			<string>entity.name.function.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])((align|offset)=)</string>
			<key>name</key>
			<string>support.function.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])[+\-]?nan((\:0[xX][\da-fA-F]+(_[\da-fA-F]+)*)?(?=[\s=();])|canonical|arithmetic)</string>
			<key>name</key>
			<string>constant.numeric.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])([+\-]?inf)(?=[\s=();])</string>
			<key>name</key>
			<string>constant.numeric.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])([+\-]?0[xX][\da-fA-F]+(_[\da-fA-F]+)*\.([\da-fA-F]+(_[\da-fA-F]+)*)*([pP][+\-]?\d+(_\d+)*)?)(?=[\s=();])</string>
			<key>name</key>
			<string>constant.numeric.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])([+\-]?0[xX][\da-fA-F]+(_[\da-fA-F]+)*[pP][+\-]?\d+(_\d+)*)(?=[\s=();])</string>
			<key>name</key>
			<string>constant.numeric.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])([+\-]?\d+(_\d+)*)(?=[\s=();])</string>
			<key>name</key>
			<string>constant.numeric.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])([+\-]?\d+(_\d+)*\.(\d+(_\d+)*)*([eE][+\-]?\d+(_\d+)*)?)(?=[\s=();])</string>
			<key>name</key>
			<string>constant.numeric.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])([+\-]?\d+(_\d+)*[eE][+\-]?\d+(_\d+)*)(?=[\s=();])</string>
			<key>name</key>
			<string>constant.numeric.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])([+\-]?0[xX][\da-fA-F]+(_[\da-fA-F]+)*)(?=[\s=();])</string>
			<key>name</key>
			<string>constant.numeric.wasm</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])\$[a-zA-Z0-9'_+*/~=&lt;&gt;!?@#$%&|:`.\-\^\\]+(?=[\s=();])</string>
			<key>name</key>
			<string>variable.parameter.function.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])\$"([^"&#10;\\]*(\\.)*)*"(?=[\s=();])</string>
			<key>name</key>
			<string>variable.parameter.function.wasm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=[\s=();])$"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.wasm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"(?=[\s=();])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.wasm</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.parameter.function.wasm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\([0-9a-fA-F]{2}|\"|\\)</string>
					<key>name</key>
					<string>constant.character.escape.wasm</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=[\s=();])"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.wasm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"(?=[\s=();])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.wasm</string>
				</dict>
			</dict>
			<key>name</key>
			<string>constant.character</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\([0-9a-fA-F]{2}|\"|\\)</string>
					<key>name</key>
					<string>constant.character.escape.wasm</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])(i8x16|i16x8|i32x4|i64x2|f32x4|f64x2)</string>
			<key>name</key>
			<string>constant.language.wasm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s=();])(i32|i64|f32|f64|v128|mut|anyfunc|funcref|externref|extern|shared)</string>
			<key>name</key>
			<string>constant.language.wasm</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.wasm</string>
	<key>uuid</key>
	<string>F01196A6-B58F-465B-A75D-4CF5D69A0019</string>
</dict>
</plist>
