#undef WASIAddressIPtr
#undef WASIADDRESSIPTR_MAX
#undef WASIADDRESSIPTR_FORMAT
#undef WAVM_DEFINE_INTRINSIC_FUNCTION_IPTR
#define WASIAddressIPtr uint32_t
#define WASIADDRESSIPTR_MAX UINT32_MAX
#define WASIADDRESSIPTR_FORMAT "0x%08x"
#define WAVM_DEFINE_INTRINSIC_FUNCTION_IPTR WAVM_DEFINE_INTRINSIC_FUNCTION

