#!/bin/bash -xe
if [ -d corpus ] ; then
    echo "Corpus already exists"
    exit 0
fi

TMPDIR=$(mktemp -d corpus_input.XXX)
mkdir -p ${TMPDIR}
cp -rf Test/spec/*.wast ${TMPDIR}

mkdir corpus
afl-cmin -i ${TMPDIR}/ -o corpus/ -m 9999999999999999999 -- ./bin/wavm --check --text @@
rm -rf ${TMPDIR}
